### PR TITLE
Print available command-line options when passing -h or --help

### PR DESCRIPTION
**Pull request by ellisgeek**
Implements half of #213.

Builds successfully on Ubuntu 14.04.
I do not have a windows machine to test on but there is no reason for it to fail on windows.

P.S. I am not a C++ dev so if I did a bad thing let me know.

### CODE REVIEW

**Comment by vktr** [comment]
Awesome! I've added you to the developers team of Hadouken giving you push access, so please merge whenever you feel ready :smile:

**Comment by Robo210** [comment]
Can you rebase your commit on top of the latest changes and try again? I think the failure here was fixed by 32426ad939c108a7da46c66e00b6edf1f01c8e9c and your change should work just fine.

**Comment by ellisgeek** [comment]
Sorry, it took me so long to get back around to this. I'm testing if it compiles with the latest changes now.

Compiling

**Comment by ellisgeek** [comment]
Build passes. Merging into Develop for inclusion in next release.

**Comment by ellisgeek** [comment]
I'm bad at this...

**Comment by vktr** [comment]
@ellisgeek Is this ready to merge?

**Comment by ellisgeek** [comment]
Yes it is ready to merge

**Pull request merged**
