### PR TITLE
Embedded UI

### PR DESCRIPTION
**Pull request by vktr**
Trying to implement a simple embedded user interface. The UI will probably be based on ruTorrent.

Also removed CORS since we don't need it when serving the UI from the same host/port as the API.

**Todo**
- [x] Implement request handlers to split http_server into several classes.
- [x] The UI request handler should be able to read static files from a `.zip` file. This makes it easier to distribute Hadouken.
- [x] Allow custom root paths to the UI (and API I guess), eg. `~/hadouken/gui` and `~/hadouken/api`.
- [x] Fix "Add URL" dialog.
- [x] Get to the bottom of the torrent status column.
- [x] Availability.
- [x] Fix branding.

### CODE REVIEW

**Comment by vktr** [comment]
Serving ruTorrent,

rutorrent

**Comment by jkaberg** [comment]
I'll just leave this to remind you ;)

Make sure http server handles reverse proxying (this is often used when haveing several web "apps" running on the same host, especially with Couchpotato/Sick-Rage and Sonarr)
Authorization/login (to web UI) - I'd suggest basic auth as it's common practice

And users should be able to change port and extention point (/gui or whatever)

:smile:

**Comment by vktr** [comment]
@jkaberg Could you give an example on how reverse proxying should work? Or why it wouldn't work right now.

As for authentication, Hadouken already supports basic authentication (for the API). The UI wouldn't need its own auth scheme. I'm just going to pop up a login dialog if we receive a 401 when calling the API.

Added path config to the todo :smile:

**Comment by jkaberg** [comment]
Well sometimes an "web app" implementation dosn't account for reverse proxys setup with an alternative "root" path, eg /mynewrootpath/<hadouken> when hadouken is expecting /<hadouken> which will then resolve all it's depedency's (css, js etc) to the absolute root (eg /<hadouken>/css/style.css when it should resolve to /mynewrootpath/<hadouken>/css/style.css) but with an path/extention option available this is resolved :)

**Comment by vktr** [comment]
@jkaberg You got it.

**Pull request merged**
